#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -LsS -f -O $PROXY $1 -o symfony; cd -
}

# Download symfony installer
URL="http://symfony.com/installer"

dl $URL /usr/local/src

mv /usr/local/src/installer /usr/local/bin/symfony
chmod a+x /usr/local/bin/symfony
