#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -LsS -f -O $PROXY $1 -o symfony; cd -
}

# download symfony cli tool
USER_REPO="symfony/cli"
VERSION=$(gh_releases ${USER_REPO} | sort -V | tail -1)
URL="https://github.com/${USER_REPO}/releases/download/${VERSION}/symfony_linux_amd64.gz"

dl $URL /usr/local/src
