#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -LsS -f -O $PROXY $1 -o symfony; cd -
}

#Installer
URL="http://symfony.com/installer"

dl $URL /usr/local/src
