#!/bin/sh -ex

NAME=symfony
DB_PASS=$(mcookie)

WEBROOT=/var/www/symfony
SRC=/usr/local/src
BIN=/usr/local/bin

# php tweaks
PHP_INI="/etc/php/7.4/apache2/php.ini /etc/php/7.4/cli/php.ini"
for php_ini in $PHP_INI; do
    # Set timezone (TODO: we should move this to an inithook)
    sed -i "s|^;date.timezone\(.*\)|date.timezone = 'America/Los_Angeles'|" $php_ini

    # Set open tag to off for php
    sed -i "s|^short_open_tag = On|short_open_tag = Off|" $php_ini

    # Up the memory from  32MB to 64MB (Issues with clear:cache command)
    sed -i "s|^memory_limit = 32M|memory_limit = 128M|" $php_ini
done

# Set up Symfony cli tool
gunzip $SRC/symfony_linux_amd64.gz
mv $SRC/symfony_linux_amd64 $BIN/symfony
chmod +x $BIN/symfony

# install LTS symfony - currently v4.4.x + a few useful modules
symfony new $WEBROOT --version=lts --no-git
chown -R www-data:www-data $WEBROOT
cd $WEBROOT
export COMPOSER_NO_INTERACTION=1
turnkey-composer require symfony/apache-pack
turnkey-composer require symfony/orm-pack
turnkey-composer require --dev symfony/maker-bundle

# for some reason, the symfony/apache-pack doesn't install when run
# non-interactively, so we'll manually download the .htaccess file
HTACCESS=public/.htaccess
GH_BIT="https://github.com/symfony/recipes-contrib/tree/"
RAW_BIT="https://raw.githubusercontent.com/symfony/recipes-contrib"
PART_URL=$(turnkey-composer recipes symfony/apache-pack \
    | grep ^installed | sed "s|^.*$GH_BIT||")
curl -o $HTACCESS -L $RAW_BIT/$PART_URL/$HTACCESS

# start mysql server
service mysql start

# create symfony database & user
mysql --batch --execute "\
    CREATE DATABASE $NAME; \
    GRANT ALL PRIVILEGES ON $NAME.* TO $NAME@localhost IDENTIFIED BY '$DB_PASS'; \
    FLUSH PRIVILEGES;"

MARIADB_V=$(apt-cache policy mariadb-server | grep Candidate | sed "s|.* 1:\([0-9\.]*\)-.*|\1|")
MYSQL_STR="mysql://$NAME:$DB_PASS@127.0.0.1:3306/$NAME?serverVersion=mariadb-$MARIADB_V"
sed -i "\|^DATABASE_URL|s|=.*|=\"$MYSQL_STR\"|" $WEBROOT/.env

# configure apache
a2dissite 000-default
a2ensite symfony
a2enmod rewrite
a2enmod headers

# Change owner to root
chown root:root -R $WEBROOT

# Set permissions so that cache and logs can be updated by apache2 user
chown -R www-data:www-data $WEBROOT/var

# apply TurnKey branding to welcome page
git apply /usr/local/src/welcome.patch
rm /usr/local/src/welcome.patch

# stop mysql
service mysql stop
