#!/bin/sh -ex

NAME=symfony
DB_PASS=$(mcookie)

WEBROOT=/var/www/symfony
LOCAL_SRC=/usr/local/src

# php tweaks
PHPINI1=/etc/php5/apache2/php.ini
PHPINI2=/etc/php5/cli/php.ini

sed -i "s|^;date.timezone\(.*\)|date.timezone = 'America/Los_Angeles'|" $PHPINI1
sed -i "s|^;date.timezone\(.*\)|date.timezone = 'America/Los_Angeles'|" $PHPINI2

sed -i "s|^short_open_tag = On|short_open_tag = Off|" $PHPINI1
sed -i "s|^short_open_tag = On|short_open_tag = Off|" $PHPINI2

# start mysql server
/etc/init.d/mysql start

# create symfony database and user
mysql --user=root --password=$MYSQL_PASS --batch --execute "\
CREATE DATABASE $NAME; \
GRANT ALL PRIVILEGES ON $NAME.* TO $NAME@localhost IDENTIFIED BY '$DB_PASS'; \
FLUSH PRIVILEGES;"

# install and configure symfony
tar -zxf /usr/local/src/Symfony*.tgz -C /var/www/
mv /var/www/Symfony $WEBROOT
chown root:root -R $WEBROOT

cat > $WEBROOT/app/config/parameters.ini << EOF
[parameters]
    database_driver   = pdo_mysql
    database_host     = localhost
    database_port     = 3036
    database_name     = symfony
    database_user     = $NAME
    database_password = $DB_PASS

    mailer_transport  = smtp
    mailer_host       = localhost
    mailer_user       =
    mailer_password   =

    locale            = en

    secret            = $(mcookie)
EOF

# verify configuration
cd $WEBROOT
php app/check.php

# tweak permissions
chown -R www-data:www-data $WEBROOT/app/cache
chown -R www-data:www-data $WEBROOT/app/logs

# create welcome page and htaccess hack
cat > $WEBROOT/web/index.php <<EOF
<?php
require_once __DIR__.'/../app/bootstrap.php.cache';
require_once __DIR__.'/../app/AppKernel.php';

use Symfony\Component\HttpFoundation\Request;

\$kernel = new AppKernel('dev', true);
\$kernel->loadClassCache();
\$kernel->handle(Request::createFromGlobals())->send();
EOF

cp $WEBROOT/web/.htaccess $WEBROOT/web/.htaccess.orig
cat > $WEBROOT/web/.htaccess <<EOF
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-f
    # RewriteRule ^(.*)$ app.php [QSA,L]
    RewriteRule ^(.*)$ index.php [QSA,L]
</IfModule>
EOF

TEMPLATE=$WEBROOT/src/Acme/DemoBundle/Resources/views/Welcome/index.html.twig
sed -i "s|<h1>\(.*\)</h1>|<h1>Welcome to TurnKey Symfony</h1>|" $TEMPLATE
sed -i "s|<p>Congratulations\(.*\)</p>|<p>Before getting started, execute the following commands:</p><pre>rm $WEBROOT/web/index.php\nmv $WEBROOT/web/{.htaccess.orig,.htaccess}\n\n</pre>|" $TEMPLATE

# configure apache
a2dissite default
a2ensite symfony
a2enmod rewrite

# stop mysql
/etc/init.d/mysql stop

# cleanup
rm -f $LOCAL_SRC/Symfony*

