#!/bin/bash -e
# Regenerate the Symfony secret key and MariaDB password.

. /etc/default/inithooks

CONF=/var/www/symfony/.env.local

sed -i "\|^APP_SECRET|s|=.*|=$(mcookie)|" "$CONF"

# set Symfony user DB password
PASSWORD=$(mcookie)
sed -i "\|^DATABASE_URL|s|mysql://symfony:.*@|mysql://symfony:${PASSWORD}@|" "$CONF"
$INITHOOKS_PATH/bin/mysqlconf.py --user=symfony --pass="$PASSWORD"
