#!/bin/bash -e
# regenerate symfony secret key and mysql password

. /etc/default/inithooks

CONF=/var/www/symfony/apps/frontend/config/settings.yml
sed -i "s/csrf_secret: \(.*\)/csrf_secret: $(mcookie)/" $CONF

PASSWORD=$(mcookie)

CONF=/var/www/symfony/config/databases.yml
sed -i "s/password: \(.*\)/password: $PASSWORD/" $CONF

$INITHOOKS_PATH/bin/mysqlconf.py --user=symfony --pass="$PASSWORD"

