ServerName localhost

<VirtualHost *:80>
    UseCanonicalName Off
    ServerAdmin webmaster@localhost
    DocumentRoot /var/www/symfony/public
</VirtualHost>

<VirtualHost *:443>
    SSLEngine on
    ServerAdmin webmaster@localhost
    DocumentRoot /var/www/symfony/public
</VirtualHost>

<Directory /var/www/symfony/public>
    AllowOverride None
    DirectoryIndex index.php
    FallbackResource /index.php
    Require all granted
</Directory>
